// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tzdjisezjmmrjvfnvint.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6ZGppc2V6am1tcmp2Zm52aW50Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk4Mjc0NDgsImV4cCI6MjA1NTQwMzQ0OH0._RZVBDeJatTrgYSu5EF_YByS23xKyPSApCpjP_NAXV8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);